---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/prometheus-operator/prometheus-operator
  ref:
    tag: v0.68.0
  ignore: |
    # Ignore everything except CRDs
    /*
    !/example/prometheus-operator-crd/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: prometheus-operator-crds
  path: ./example/prometheus-operator-crd
  prune: true
  wait: true
  timeout: 5m