apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/glefer
  - glefer-image-automation.yaml
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
  - path: glefer-ingress-patch.yaml
    target:
      kind: Ingress
      name: nginx
