apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: glefer
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonAnnotations:
  app.kubernetes.io/version: "1.0.0"
